services:
  mesh-dragonfly-dev:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    container_name: mesh-dragonfly-dev # Override the default name, as Docker adds index to the default name (eg. portal-redis-e2e-1) 
    ulimits:
      memlock: -1
    # Don't use all threads, occasionally fails with "There are 20 threads, so 5.00GiB are required. Exiting..."
    command: dragonfly --proactor_threads=3
    ports:
      - "6381:6379"
    # For better performance, consider `host` mode instead `port` to avoid docker NAT.
    # `host` mode is NOT currently supported in Swarm Mode.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    # network_mode: "host"
    volumes:
      - dragonflymeshdata:/mesh-dev-data
    networks:
      - portal-internal-network-2

  portal-dragonfly-dev:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    container_name: portal-dragonfly-dev # Override the default name, as Docker adds index to the default name (eg. portal-redis-e2e-1) 
    ulimits:
      memlock: -1
    # Don't use all threads, occasionally fails with "There are 20 threads, so 5.00GiB are required. Exiting..."
    command: dragonfly --proactor_threads=3
    ports:
      - "6350:6379"
    # For better performance, consider `host` mode instead `port` to avoid docker NAT.
    # `host` mode is NOT currently supported in Swarm Mode.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    # network_mode: "host"
    volumes:
      - dragonflyportaldata:/portal-dev-data
    networks:
      - portal-internal-network-2

  mesh-postgres-dev:
    image: postgres:18.3-alpine
    restart: always
    container_name: mesh-postgres-dev
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: dev-password
      POSTGRES_DB: dev-db
    ports:
      - "5434:5432"
    volumes:
      - mesh-pgdata-dev:/var/lib/postgresql/data
    networks:
      - portal-internal-network-2

# *******************************************************************************
# *** Networks
# *******************************************************************************
networks:
  portal-internal-network-2:
    driver: bridge
    
# *******************************************************************************
# *** Volumes
# *******************************************************************************
volumes:
  dragonflymeshdata:
  dragonflyportaldata:
  mesh-pgdata-dev:
