services:
  portal-redis-e2e:
    image: redis:8.0.1
    command: redis-server --requirepass e2e-redis-password
    restart: always
    container_name: portal-redis-e2e # Override the default name, as Docker adds index to the default name (eg. portal-redis-e2e-1) 
    ports:
      - 6351:6379

  portal-pg-e2e:
    image: postgres:17.0
    restart: always
    container_name: portal-pg-e2e # Override the default name, as Docker adds index to the default name (eg. portal-redis-e2e-1) 
    ports:
      - 5401:5432
    environment:
      # Make sure these matches your env file
      POSTGRES_USER: portal-db-user
      POSTGRES_PASSWORD: non-important-password
      POSTGRES_DB: portal
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ../../pgdata/portal:/var/lib/postgresql/data

  mesh-dragonfly-e2e:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    container_name: mesh-dragonfly-e2e # Override the default name, as Docker adds index to the default name (eg. portal-redis-e2e-1) 
    ulimits:
      memlock: -1
    ports:
      - "6381:6379"
    # For better performance, consider `host` mode instead `port` to avoid docker NAT.
    # `host` mode is NOT currently supported in Swarm Mode.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    # network_mode: "host"
    volumes:
      - dragonflydata:/data
volumes:
  dragonflydata: